/**
 * Production macOS .app build pipeline.
 *
 * Neutralino does not produce a .app bundle on its own — `neu build`
 * emits dist/agent-dock/bin/neutralino-mac_<arch> + resources.neu +
 * the web bundle. This script assembles the .app skeleton:
 *
 *   agent-dock.app/
 *     Contents/
 *       Info.plist
 *       MacOS/
 *         agent-dock      Mach-O launcher (compiled scripts/launcher.swift)
 *       Resources/
 *         appIcon.icns
 *         neutralino      copy of bin/neutralino-mac_<arch>
 *         resources.neu   Neutralino bundle (must sit next to neutralino)
 *         index.html, assets/   web build
 *         api/dist/, api/package.json, node_modules/   embedded API
 *         launch-api.mjs  Node shim that runs the API
 *
 * v1 strategy: the Swift launcher invokes the host's system `node` to
 * run launch-api.mjs in the background, then chdir+execs the Neutralino
 * binary so neu finds resources.neu adjacent in cwd. README documents
 * the Node 20+ prerequisite. The launcher is a Mach-O — bash-script
 * CFBundleExecutables fail Sequoia Gatekeeper ("no usable signature").
 */
import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, cpSync, existsSync, lstatSync, mkdirSync, readdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const REPO = path.resolve(import.meta.dirname, "..");
const APP_NAME = "agent-dock.app";
const NEU_OUT = path.join(REPO, "dist", "agent-dock");
const APP = path.join(REPO, "dist", APP_NAME);
const RESOURCES_DIR = path.join(REPO, "resources");
const WEB_DIST = path.join(REPO, "apps", "web", "dist");

function run(label, cmd, args, opts = {}) {
  console.log(`\n▸ ${label}`);
  const r = spawnSync(cmd, args, { stdio: "inherit", cwd: REPO, ...opts });
  if (r.status !== 0) {
    console.error(`✗ ${label} failed (exit ${r.status})`);
    process.exit(r.status ?? 1);
  }
}

run("clean stale dist/agent-dock and dist/agent-dock.app", "rm", ["-rf", NEU_OUT, APP]);

// Build packages + API + web first (no neu yet); neu's resources.neu
// must be bundled from the *patched* web output, not the dev shell.
run("build packages", "npm", ["run", "build:packages"]);
run("build api", "npm", ["run", "build", "-w", "@agent-dock/api"]);
run("build web", "npm", ["run", "build", "-w", "@agent-dock/web"]);

// Stage the built web bundle into /resources/ so 'neu build' bundles
// the right index.html + /assets/ into resources.neu. Restore /resources/
// afterward so dev mode (npm run dev) keeps its untouched dev shell.
console.log("\n▸ stage web build into /resources/ for neu bundling");
const stagedNames = new Set(readdirSync(WEB_DIST));
const preStaged = readdirSync(RESOURCES_DIR);
const backup = path.join(REPO, "dist", ".resources-backup");
rmSync(backup, { recursive: true, force: true });
mkdirSync(backup, { recursive: true });
for (const name of preStaged) {
  if (stagedNames.has(name)) {
    cpSync(path.join(RESOURCES_DIR, name), path.join(backup, name), { recursive: true });
  }
}
for (const name of stagedNames) {
  rmSync(path.join(RESOURCES_DIR, name), { recursive: true, force: true });
  cpSync(path.join(WEB_DIST, name), path.join(RESOURCES_DIR, name), { recursive: true });
}

// Inject Neutralino's two required script tags into the staged
// index.html. Vite produces a clean index.html with no Neutralino
// refs; both files are needed at runtime:
//   __neutralino_globals.js — generated by the Neutralino web
//     server, sets window.NL_TOKEN/NL_PORT/etc.
//   neutralino.js          — the client library that uses those
//     globals to connect over WebSocket and expose
//     window.Neutralino.* (folder picker, native APIs, etc.).
// neu's bootstrap only *patches* existing tags via regex; it never
// injects them, so the prebuilt index.html must include them.
console.log("▸ inject Neutralino script tags into index.html");
const stagedIndex = path.join(RESOURCES_DIR, "index.html");
const indexHtml = readFileSync(stagedIndex, "utf8");
const NEU_TAGS = [
  '<script src="neutralino.js"></script>',
  '<script src="__neutralino_globals.js"></script>',
];
const missing = NEU_TAGS.filter((tag) => !indexHtml.includes(tag));
if (missing.length > 0) {
  writeFileSync(stagedIndex, indexHtml.replace("</head>", `  ${missing.join("\n  ")}\n  </head>`));
}

if (!existsSync(path.join(RESOURCES_DIR, "neutralino.js"))) {
  console.error(
    "\n✗ resources/neutralino.js missing. Run 'npx @neutralinojs/neu update' first" +
      " — neu only downloads the client library when cli.clientLibrary is set in" +
      " neutralino.config.json.",
  );
  process.exit(1);
}

let neuFailed = null;
try {
  run("build neu", "npm", ["run", "neutralino:build"]);
} catch (err) {
  neuFailed = err;
} finally {
  console.log("\n▸ restore /resources/ to dev shell");
  for (const name of stagedNames) {
    rmSync(path.join(RESOURCES_DIR, name), { recursive: true, force: true });
  }
  for (const name of readdirSync(backup)) {
    cpSync(path.join(backup, name), path.join(RESOURCES_DIR, name), { recursive: true });
  }
  rmSync(backup, { recursive: true, force: true });
}
if (neuFailed) throw neuFailed;

if (!existsSync(NEU_OUT)) {
  console.error(`\n✗ Expected neu build to produce ${NEU_OUT}; not found.`);
  process.exit(1);
}

const arch = process.arch === "arm64" ? "arm64" : "x64";
const neuBinSrc = path.join(NEU_OUT, "bin", `neutralino-mac_${arch}`);
if (!existsSync(neuBinSrc)) {
  console.error(`\n✗ Missing ${neuBinSrc}. Run 'npx @neutralinojs/neu update' first.`);
  process.exit(1);
}

console.log(`\n▸ scaffold ${APP_NAME}`);
const macOS = path.join(APP, "Contents", "MacOS");
const resources = path.join(APP, "Contents", "Resources");
mkdirSync(macOS, { recursive: true });
mkdirSync(resources, { recursive: true });

// Compile the Swift Mach-O launcher (replaces the previous bash shim
// at Contents/MacOS/agent-dock). Sequoia Gatekeeper rejects bash-
// script CFBundleExecutables with "no usable signature" even when the
// bundle is correctly signed and notarized.
console.log("▸ compile Swift launcher (swiftc)");
const launcherTmp = path.join(tmpdir(), `agent-dock-launcher-${process.pid}`);
const swiftcResult = spawnSync(
  "swiftc",
  ["-O", "-target", "arm64-apple-macos11", "-o", launcherTmp, path.join(REPO, "scripts", "launcher.swift")],
  { stdio: "inherit" },
);
if (swiftcResult.status !== 0) {
  console.error("\n✗ swiftc failed. If the Xcode CLI tools are missing, run `xcode-select --install`.");
  process.exit(swiftcResult.status ?? 1);
}

console.log("▸ copy Neutralino binary into Contents/Resources/neutralino");
cpSync(neuBinSrc, path.join(resources, "neutralino"));
chmodSync(path.join(resources, "neutralino"), 0o755);

// Neutralino's binary looks for resources.neu *next to itself*, not
// inside the bundle root. The Swift launcher chdir's to
// Contents/Resources/ before exec'ing the Neutralino binary, so
// placing resources.neu here keeps Neutralino's adjacency requirement
// satisfied while moving non-CFBundleExecutable files out of MacOS/
// (which is mandated by macOS bundle conventions and required for
// codesign + Gatekeeper to evaluate the bundle correctly).
console.log("▸ copy resources.neu next to the Neutralino binary (Contents/Resources/resources.neu)");
cpSync(path.join(NEU_OUT, "bin", "resources.neu"), path.join(resources, "resources.neu"));

console.log("▸ copy patched web bundle into Contents/Resources (fallback)");
for (const entry of ["index.html", "assets", "agent-dock.svg"]) {
  const src = path.join(NEU_OUT, entry);
  if (existsSync(src)) {
    cpSync(src, path.join(resources, entry), { recursive: true });
  }
}

console.log("▸ embed API + node_modules");
cpSync(path.join(REPO, "apps", "api", "dist"), path.join(resources, "api", "dist"), { recursive: true });
cpSync(path.join(REPO, "apps", "api", "package.json"), path.join(resources, "api", "package.json"));
cpSync(path.join(REPO, "node_modules"), path.join(resources, "node_modules"), { recursive: true, dereference: true });

// Strip node_modules/.bin/ directories — they contain symlinks/scripts
// for build-time tools (vite, esbuild, etc.) that the runtime API
// never invokes. codesign --deep --strict flags these symlinks as
// "modified" during verification, breaking signed builds. Removing
// them also shaves bundle size.
console.log("▸ strip node_modules/.bin/ trees (build-time tools, not needed at runtime)");
function stripBinDirs(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) continue;
    if (!entry.isDirectory()) continue;
    const full = path.join(dir, entry.name);
    if (entry.name === ".bin") {
      rmSync(full, { recursive: true, force: true });
      continue;
    }
    stripBinDirs(full);
  }
}
stripBinDirs(path.join(resources, "node_modules"));

// fs.cp's `dereference: true` does not reliably dereference workspace
// symlinks (npm links @agent-dock/* into node_modules as either relative
// or absolute symlinks; on copy they survive as absolute symlinks into
// the dev tree, which then 404s on any other machine). Explicitly
// replace each workspace symlink with a real copy of {dist, package.json}
// — that's all the runtime needs; src/ and node_modules/ inside each
// package would just bloat the bundle.
console.log("▸ materialise workspace packages (replace @agent-dock/* symlinks)");
const workspaceLinkDir = path.join(resources, "node_modules", "@agent-dock");
for (const name of readdirSync(workspaceLinkDir)) {
  const linkPath = path.join(workspaceLinkDir, name);
  const stat = lstatSync(linkPath);
  if (!stat.isSymbolicLink()) continue;
  const realTarget = realpathSync(linkPath);
  rmSync(linkPath, { recursive: true, force: true });
  mkdirSync(linkPath, { recursive: true });
  for (const sub of ["dist", "package.json"]) {
    const src = path.join(realTarget, sub);
    if (existsSync(src)) {
      cpSync(src, path.join(linkPath, sub), { recursive: true });
    }
  }
}

console.log("▸ write API launcher (launch-api.mjs)");
writeFileSync(
  path.join(resources, "launch-api.mjs"),
  `#!/usr/bin/env node
import { spawn } from "node:child_process";
import { mkdirSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));

const dataDir = process.env.AGENT_DOCK_DATA_DIR ?? path.join(os.homedir(), ".agent-dock");
const artifactDir = process.env.AGENT_DOCK_ARTIFACT_DIR ?? path.join(dataDir, "artifacts");
mkdirSync(dataDir, { recursive: true });
mkdirSync(artifactDir, { recursive: true });

const child = spawn(process.execPath, [path.join(here, "api", "dist", "index.js")], {
  stdio: "inherit",
  cwd: dataDir,
  env: {
    ...process.env,
    AGENT_DOCK_PRODUCTION: "1",
    AGENT_DOCK_DATA_DIR: dataDir,
    AGENT_DOCK_ARTIFACT_DIR: artifactDir,
    NODE_PATH: path.join(here, "node_modules"),
  },
});
child.on("exit", (code) => process.exit(code ?? 0));
`,
  { mode: 0o755 },
);

console.log("▸ install compiled Swift launcher as Contents/MacOS/agent-dock");
cpSync(launcherTmp, path.join(macOS, "agent-dock"));
chmodSync(path.join(macOS, "agent-dock"), 0o755);
rmSync(launcherTmp, { force: true });

console.log("▸ copy icon and write Info.plist");
cpSync(path.join(REPO, "resources", "icon.icns"), path.join(resources, "appIcon.icns"));
const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Agent*Dock</string>
  <key>CFBundleDisplayName</key><string>Agent*Dock</string>
  <key>CFBundleIdentifier</key><string>dev.agent-dock.app</string>
  <key>CFBundleVersion</key><string>0.1.0</string>
  <key>CFBundleShortVersionString</key><string>0.1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>agent-dock</string>
  <key>CFBundleIconFile</key><string>appIcon</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>LSUIElement</key><false/>
  <key>LSBackgroundOnly</key><false/>
  <key>NSAppleEventsUsageDescription</key><string>Agent*Dock launches its local API process to coordinate sessions.</string>
</dict>
</plist>
`;
writeFileSync(path.join(APP, "Contents", "Info.plist"), plist);

// Detach the build's quarantine flag so local launches don't trigger Gatekeeper while you're iterating.
try {
  execFileSync("xattr", ["-cr", APP]);
} catch {
  /* harmless; release flow re-quarantines anyway */
}

// Codesign. If APPLE_DEVELOPER_ID is set (release flow), defer to
// scripts/sign-mac.mjs which signs inside-out with hardened runtime
// + entitlements (suitable for notarization). Otherwise ad-hoc sign
// — works on the build machine and on other Macs after a one-click
// "Open Anyway" in System Settings → Privacy & Security.
const isReleaseSign = process.argv.includes("--sign");
if (isReleaseSign) {
  console.log("▸ release codesign via scripts/sign-mac.mjs");
  execFileSync(process.execPath, [path.join(REPO, "scripts", "sign-mac.mjs"), APP], { stdio: "inherit" });
} else {
  console.log("▸ ad-hoc codesign the .app (no Developer ID — pass --sign for release)");
  try {
    execFileSync("codesign", ["--force", "--deep", "--sign", "-", APP], { stdio: "inherit" });
  } catch (err) {
    console.warn(`  warn: codesign failed (${err.message}). The app will still run on the build machine but is more likely to be blocked by Gatekeeper on other Macs.`);
  }
}

console.log(`\n✓ ${APP_NAME} ready at ${APP}`);
console.log("  Smoke run: open dist/agent-dock.app");
console.log("  Then:      tail -f ~/Library/Logs/agent-dock-api.log");
console.log("\nNext: npm run package:dmg to wrap into a draggable installer.");
