import type { Game } from "@/games/types";

export const bugHunter: Game = {
  id: "bug-hunter",
  title: "Bug Hunter",
  subtitle: "Python Fundamentals",
  description: "Review tiny broken snippets and ship the correct fix.",
  accent: "PY",
  notes: [
    [":", "if, for, while, and def headers end with a colon."],
    ["indentation", "Python blocks are defined by consistent indentation."],
    ["names", "Variables must be defined before they are used."],
    ["list[0]", "Lists use zero-based indexes."],
    ['dict["key"]', "Dictionary values are read by key."],
    ["return", "Functions send values back with return."],
    ["for item in items", "Use the loop variable inside the loop body."],
    ["==", "Use equality comparison in conditions."],
  ],
  levels: [
    {
      id: 1,
      title: "Gate Colon",
      concept: "Missing colon",
      mode: "choice",
      prompt: "Fix the syntax error in this conditional.",
      code: "if lives > 0\n    print('keep going')",
      answer: "colon",
      hint: "Python block headers need punctuation at the end.",
      explanation: "if lives > 0: starts the indented block correctly.",
      choices: [
        { id: "colon", label: "Add a colon after the condition", code: "if lives > 0:" },
        { id: "semi", label: "Add a semicolon after print", code: "print('keep going');" },
        { id: "paren", label: "Remove parentheses from print", code: "print 'keep going'" },
      ],
    },
    {
      id: 2,
      title: "Indent Alarm",
      concept: "Indentation",
      mode: "choice",
      prompt: "Choose the fix that makes the print part of the loop.",
      code: "for item in items:\nprint(item)",
      answer: "indent",
      hint: "The loop body must be indented.",
      explanation: "Indenting print(item) places it inside the for loop block.",
      choices: [
        { id: "indent", label: "Indent the print line", code: "for item in items:\n    print(item)" },
        { id: "unindent", label: "Remove the colon", code: "for item in items\nprint(item)" },
        { id: "rename", label: "Rename item to items", code: "print(items)" },
      ],
    },
    {
      id: 3,
      title: "Name Scanner",
      concept: "Undefined variable",
      mode: "choice",
      prompt: "Fix the undefined name bug.",
      code: "score = 10\nprint(points)",
      answer: "score",
      hint: "Print the variable that actually exists.",
      explanation: "score is defined; points is not.",
      choices: [
        { id: "score", label: "Use score in print", code: "print(score)" },
        { id: "quote", label: "Quote points", code: "print('points')" },
        { id: "delete", label: "Delete score", code: "print(points)" },
      ],
    },
    {
      id: 4,
      title: "First Apple",
      concept: "List index basics",
      mode: "choice",
      prompt: "Fix this snippet so it prints the first apple.",
      code: "apples = ['red', 'green']\nprint(apples[1])",
      answer: "zero",
      hint: "The first item is at index 0.",
      explanation: "apples[0] reads the first list item.",
      choices: [
        { id: "zero", label: "Change index to 0", code: "print(apples[0])" },
        { id: "two", label: "Change index to 2", code: "print(apples[2])" },
        { id: "name", label: "Use apples.first", code: "print(apples.first)" },
      ],
    },
    {
      id: 5,
      title: "Key Card",
      concept: "Dictionary access",
      mode: "choice",
      prompt: "Fix the dictionary access.",
      code: "user = {'name': 'Ada'}\nprint(user.name)",
      answer: "brackets",
      hint: "Dictionaries use bracket access with a key.",
      explanation: "user['name'] reads the value stored under the name key.",
      choices: [
        { id: "brackets", label: "Use bracket key access", code: "print(user['name'])" },
        { id: "call", label: "Call user as a function", code: "print(user('name'))" },
        { id: "index", label: "Use numeric index", code: "print(user[0])" },
      ],
    },
    {
      id: 6,
      title: "Return Dock",
      concept: "Function return",
      mode: "choice",
      prompt: "Fix the function so result receives the doubled value.",
      code: "def double(n):\n    n * 2\n\nresult = double(4)",
      answer: "return",
      hint: "Expressions inside a function are not returned automatically.",
      explanation: "return n * 2 sends the computed value back to the caller.",
      choices: [
        { id: "return", label: "Add return", code: "def double(n):\n    return n * 2" },
        { id: "print", label: "Print inside the function", code: "def double(n):\n    print(n * 2)" },
        { id: "global", label: "Make n global", code: "global n" },
      ],
    },
    {
      id: 7,
      title: "Loop Signal",
      concept: "Loop variable usage",
      mode: "choice",
      prompt: "Fix the loop to print each name.",
      code: "names = ['Ada', 'Lin']\nfor name in names:\n    print(names)",
      answer: "variable",
      hint: "Use the current item, not the whole list.",
      explanation: "print(name) prints each loop item one at a time.",
      choices: [
        { id: "variable", label: "Print the loop variable", code: "print(name)" },
        { id: "range", label: "Print range(names)", code: "print(range(names))" },
        { id: "string", label: "Print the word name", code: "print('name')" },
      ],
    },
    {
      id: 8,
      title: "Compare Trap",
      concept: "Equality comparison",
      mode: "choice",
      prompt: "Fix the condition so it compares the status.",
      code: "if status = 'ready':\n    launch()",
      answer: "equals",
      hint: "Conditions compare with two equals signs.",
      explanation: "status == 'ready' compares values; = is assignment syntax.",
      choices: [
        { id: "equals", label: "Use ==", code: "if status == 'ready':" },
        { id: "triple", label: "Use ===", code: "if status === 'ready':" },
        { id: "arrow", label: "Use =>", code: "if status => 'ready':" },
      ],
    },
  ],
};
