import type { Game } from "@/games/types";

export const commandBuilder: Game = {
  id: "command-builder",
  title: "Command Builder",
  subtitle: "Bash Fundamentals",
  description: "Build the right shell command from prompt and file context.",
  accent: "SH",
  notes: [
    ["ls", "List files in the current directory."],
    ["*", "Match zero or more characters in a filename."],
    ["?", "Match exactly one character in a filename."],
    ["grep", "Search files for matching text."],
    ["grep -i", "Search without matching letter case."],
    ["grep -n", "Show line numbers with matches."],
    ["grep -r", "Search recursively through directories."],
    ["sed 's/a/b/'", "Print text with the first match on each line replaced."],
    ["sed -n '1,3p'", "Print only a selected line range."],
    ["wc -l", "Count lines from input."],
    ["find", "Search directories by rules such as name patterns."],
  ],
  levels: [
    {
      id: 1,
      title: "List Files",
      concept: "ls basics",
      mode: "typed",
      prompt: "List all files in the current directory.",
      files: ["app.log", "server.log", "notes.txt"],
      answer: "ls",
      acceptedAnswers: ["ls"],
      hint: "Use the command that lists directory contents.",
      explanation: "ls lists files in the current directory.",
    },
    {
      id: 2,
      title: "Glob Logs",
      concept: "Wildcards",
      mode: "typed",
      prompt: "List all .log files.",
      files: ["app.log", "server.log", "notes.txt"],
      answer: "ls *.log",
      acceptedPatterns: [/^ls \*\.log$/],
      hint: "Use ls with a wildcard pattern for log files.",
      explanation: "ls *.log lists files whose names end with .log.",
    },
    {
      id: 3,
      title: "Grep Errors",
      concept: "grep basics",
      mode: "typed",
      prompt: 'Find "error" in .log files.',
      files: ["app.log", "server.log", "notes.txt"],
      answer: "grep error *.log",
      acceptedPatterns: [/^grep ("error"|'error'|error) \*\.log$/],
      hint: "Use grep, the search term, and the *.log wildcard.",
      explanation: "grep error *.log searches every matching log file for the text error.",
    },
    {
      id: 4,
      title: "Count Lines",
      concept: "Pipes + wc",
      mode: "typed",
      prompt: "Count lines in app.log.",
      files: ["app.log"],
      answer: "cat app.log | wc -l",
      acceptedPatterns: [/^cat app\.log \| wc -l$/],
      hint: "Pipe the file contents into wc -l.",
      explanation: "cat app.log | wc -l sends the file contents to wc, which counts lines with -l.",
    },
    {
      id: 5,
      title: "Scripts Folder",
      concept: "Path globs",
      mode: "typed",
      prompt: "List JavaScript files in the scripts directory.",
      files: ["scripts/app.js", "scripts/build.js", "styles/app.css", "README.md"],
      answer: "ls scripts/*.js",
      acceptedAnswers: ["ls scripts/*.js"],
      hint: "Use ls with a directory name and a *.js glob.",
      explanation: "ls scripts/*.js lists files ending in .js inside the scripts directory.",
    },
    {
      id: 6,
      title: "Report Files",
      concept: "Prefix + suffix glob",
      mode: "typed",
      prompt: "List files whose names start with report- and end in .txt.",
      files: ["report-1.txt", "report-2.txt", "report-final.md", "notes.txt"],
      answer: "ls report-*.txt",
      acceptedAnswers: ["ls report-*.txt"],
      hint: "Use a glob that fixes the report- prefix and .txt suffix.",
      explanation: "ls report-*.txt matches any filename that starts with report- and ends with .txt.",
    },
    {
      id: 7,
      title: "Single Digit",
      concept: "? wildcard",
      mode: "typed",
      prompt: "List day files that use a single digit, like day1.txt.",
      files: ["day1.txt", "day2.txt", "day10.txt", "notes.txt"],
      answer: "ls day?.txt",
      acceptedAnswers: ["ls day?.txt"],
      hint: "Use ? when exactly one character can vary.",
      explanation: "ls day?.txt matches day1.txt and day2.txt, but not day10.txt because ? is one character.",
    },
    {
      id: 8,
      title: "Recursive Find",
      concept: "find -name",
      mode: "typed",
      prompt: "Find all .txt files recursively.",
      files: ["notes.txt", "docs/readme.txt", "logs/app.log"],
      answer: 'find . -name "*.txt"',
      acceptedPatterns: [/^find \. -name ("\*\.txt"|'\*\.txt')$/],
      hint: 'Use find from the current directory with -name "*.txt".',
      explanation: 'find . -name "*.txt" searches recursively from the current directory for .txt files.',
    },
    {
      id: 9,
      title: "Warning Hunt",
      concept: "grep target file",
      mode: "typed",
      prompt: 'Find "warning" in app.log.',
      files: ["app.log", "server.log", "notes.txt"],
      answer: "grep warning app.log",
      acceptedPatterns: [/^grep ("warning"|'warning'|warning) app\.log$/],
      hint: "Use grep with the search text and the target filename.",
      explanation: "grep warning app.log searches app.log for lines containing warning.",
    },
    {
      id: 10,
      title: "Case Insensitive",
      concept: "grep -i flag",
      mode: "typed",
      prompt: 'Find "error" in app.log, ignoring uppercase and lowercase.',
      files: ["app.log", "server.log"],
      answer: "grep -i error app.log",
      acceptedPatterns: [/^grep -i ("error"|'error'|error) app\.log$/],
      hint: "Add the -i flag to grep for a case-insensitive search.",
      explanation: "grep -i error app.log finds error, ERROR, Error, and other case variations.",
    },
    {
      id: 11,
      title: "Line Numbers",
      concept: "grep -n flag",
      mode: "typed",
      prompt: 'Find "todo" in notes.txt and show line numbers.',
      files: ["notes.txt", "tasks.md"],
      answer: "grep -n todo notes.txt",
      acceptedPatterns: [/^grep -n ("todo"|'todo'|todo) notes\.txt$/],
      hint: "Use grep with the -n flag to include line numbers.",
      explanation: "grep -n todo notes.txt prints matching lines with their line numbers.",
    },
    {
      id: 12,
      title: "Recursive grep",
      concept: "grep -r flag",
      mode: "typed",
      prompt: 'Search recursively for "TODO" from the current directory.',
      files: ["src/app.js", "src/helpers.js", "README.md"],
      answer: "grep -r TODO .",
      acceptedPatterns: [/^grep -r ("TODO"|'TODO'|TODO) \.$/],
      hint: "Use grep -r and search from the current directory.",
      explanation: "grep -r TODO . recursively searches files below the current directory.",
    },
    {
      id: 13,
      title: "Substitute First",
      concept: "sed substitution",
      mode: "typed",
      prompt: "Replace error with warning when printing app.log.",
      files: ["app.log"],
      answer: "sed 's/error/warning/' app.log",
      acceptedAnswers: [
        "sed 's/error/warning/' app.log",
        'sed "s/error/warning/" app.log',
      ],
      hint: "Use sed with a substitute expression: s/old/new/.",
      explanation: "sed 's/error/warning/' app.log replaces the first error on each printed line with warning.",
    },
    {
      id: 14,
      title: "Substitute Global",
      concept: "sed g flag",
      mode: "typed",
      prompt: "Replace every error on each line with warning.",
      files: ["app.log"],
      answer: "sed 's/error/warning/g' app.log",
      acceptedAnswers: [
        "sed 's/error/warning/g' app.log",
        'sed "s/error/warning/g" app.log',
      ],
      hint: "Add g at the end of the sed substitution to replace globally on each line.",
      explanation: "sed 's/error/warning/g' app.log replaces every error occurrence on each line.",
    },
    {
      id: 15,
      title: "Print Range",
      concept: "sed -n range",
      mode: "typed",
      prompt: "Print only lines 1 through 3 from app.log.",
      files: ["app.log"],
      answer: "sed -n '1,3p' app.log",
      acceptedAnswers: [
        "sed -n '1,3p' app.log",
        'sed -n "1,3p" app.log',
      ],
      hint: "Use sed -n with a 1,3p range.",
      explanation: "sed -n '1,3p' app.log suppresses default output and prints only lines 1 through 3.",
    },
  ],
};
