import type { Game } from "@/games/types";

export const typeDungeon: Game = {
  id: "type-dungeon",
  title: "Type Dungeon",
  subtitle: "TypeScript Fundamentals",
  description: "Unlock doors by choosing the type-safe move.",
  accent: "TS",
  notes: [
    ['"prop" in value', "Narrows a union to members that contain that property."],
    ["typeof", "Checks primitive runtime types such as string or number."],
    ["?.", "Safely reads through null or undefined values."],
    ["Readonly<T>", "Prevents assigning to properties on T."],
    ["Partial<T>", "Makes every property optional."],
    ["Box<T>", "Keeps the wrapped value type connected to T."],
    ["structural typing", "Objects match interfaces by shape."],
    ["Promise<T>", "Describes an async value that resolves to T."],
  ],
  levels: [
    {
      id: 1,
      title: "Mage Door",
      concept: "Union narrowing",
      mode: "choice",
      prompt: "Enemy can be an Orc or Mage. Which check safely narrows before reading mana?",
      code: "type Enemy = Orc | Mage;\n// Mage has mana, Orc does not.",
      answer: "in",
      hint: "Check whether the property exists on the union value.",
      explanation: 'The "mana" in enemy check narrows the union to members that have mana.',
      choices: [
        { id: "in", label: 'if ("mana" in enemy)', code: 'if ("mana" in enemy) enemy.mana' },
        { id: "cast", label: "if (enemy as Mage)", code: "(enemy as Mage).mana" },
        { id: "truthy", label: "if (enemy)", code: "if (enemy) enemy.mana" },
      ],
    },
    {
      id: 2,
      title: "String Gate",
      concept: "typeof narrowing",
      mode: "choice",
      prompt: "value is string | number. Which guard lets you call toUpperCase safely?",
      code: "function shout(value: string | number) { ... }",
      answer: "typeof",
      hint: "Use the runtime primitive type check.",
      explanation: 'typeof value === "string" narrows value to string.',
      choices: [
        { id: "length", label: "if (value.length)", code: "if (value.length) value.toUpperCase()" },
        { id: "typeof", label: 'if (typeof value === "string")', code: 'if (typeof value === "string") value.toUpperCase()' },
        { id: "string", label: 'if (value === "string")', code: 'if (value === "string") value.toUpperCase()' },
      ],
    },
    {
      id: 3,
      title: "Null Bridge",
      concept: "Optional chaining",
      mode: "choice",
      prompt: "profile may be undefined. Which expression safely reads the city?",
      code: "type Profile = { address?: { city: string } };\nconst profile: Profile | undefined = getProfile();",
      answer: "optional",
      hint: "Use the operator that stops when the left side is nullish.",
      explanation: "profile?.address?.city safely returns undefined if any step is missing.",
      choices: [
        { id: "direct", label: "profile.address.city", code: "profile.address.city" },
        { id: "optional", label: "profile?.address?.city", code: "profile?.address?.city" },
        { id: "non-null", label: "profile!.address!.city", code: "profile!.address!.city" },
      ],
    },
    {
      id: 4,
      title: "Stone Contract",
      concept: "Readonly<T>",
      mode: "choice",
      prompt: "Which type prevents changing user.name after creation?",
      code: "type User = { name: string; role: string };",
      answer: "readonly",
      hint: "Look for the utility that marks properties immutable.",
      explanation: "Readonly<User> makes User properties read-only at compile time.",
      choices: [
        { id: "partial", label: "Partial<User>", code: "Partial<User>" },
        { id: "readonly", label: "Readonly<User>", code: "Readonly<User>" },
        { id: "promise", label: "Promise<User>", code: "Promise<User>" },
      ],
    },
    {
      id: 5,
      title: "Draft Scroll",
      concept: "Partial<T>",
      mode: "choice",
      prompt: "Which type allows an update object with only some User fields?",
      code: "type User = { name: string; role: string; active: boolean };",
      answer: "partial",
      hint: "Use the utility that makes every property optional.",
      explanation: "Partial<User> is useful for patch-style updates where fields can be omitted.",
      choices: [
        { id: "readonly", label: "Readonly<User>", code: "Readonly<User>" },
        { id: "partial", label: "Partial<User>", code: "Partial<User>" },
        { id: "array", label: "User[]", code: "User[]" },
      ],
    },
    {
      id: 6,
      title: "Box Chamber",
      concept: "Generics",
      mode: "choice",
      prompt: "Which function preserves the input type inside Box<T>?",
      code: "type Box<T> = { value: T };",
      answer: "generic",
      hint: "The type parameter should appear in both the argument and return type.",
      explanation: "wrap<T>(value: T): Box<T> connects the input type to the boxed output type.",
      choices: [
        { id: "any", label: "function wrap(value: any): Box<any>", code: "function wrap(value: any): Box<any>" },
        { id: "string", label: "function wrap(value: string): Box<string>", code: "function wrap(value: string): Box<string>" },
        { id: "generic", label: "function wrap<T>(value: T): Box<T>", code: "function wrap<T>(value: T): Box<T>" },
      ],
    },
    {
      id: 7,
      title: "Shape Lock",
      concept: "Structural typing",
      mode: "choice",
      prompt: "Which object is compatible with Named?",
      code: "interface Named { name: string }",
      answer: "extra",
      hint: "TypeScript checks shape, and extra properties can still be okay in assigned values.",
      explanation: "An object with name: string matches Named even if it also has extra properties.",
      choices: [
        { id: "missing", label: "{ id: 1 }", code: "{ id: 1 }" },
        { id: "wrong", label: "{ name: 42 }", code: "{ name: 42 }" },
        { id: "extra", label: '{ name: "Ada", id: 1 }', code: '{ name: "Ada", id: 1 }' },
      ],
    },
    {
      id: 8,
      title: "Async Portal",
      concept: "Promise<T>",
      mode: "choice",
      prompt: "An async function returns a user. What return type describes it?",
      code: 'async function loadUser() { return { name: "Ada" }; }',
      answer: "promise",
      hint: "Async functions always return promises.",
      explanation: "Promise<User> describes an async result that resolves to User.",
      choices: [
        { id: "user", label: "User", code: "User" },
        { id: "promise", label: "Promise<User>", code: "Promise<User>" },
        { id: "partial", label: "Partial<User>", code: "Partial<User>" },
      ],
    },
  ],
};
