import type { Game } from "@/games/types";

export const vimNinja: Game = {
  id: "vim-ninja",
  title: "Vim Ninja",
  subtitle: "Vim Fundamentals",
  description: "Type the motion or operator that slices the target.",
  accent: "VI",
  notes: [
    ["h", "Move left."],
    ["j", "Move down."],
    ["k", "Move up."],
    ["l", "Move right."],
    ["w", "Jump to the next word."],
    ["b", "Jump back to the previous word."],
    ["0", "Move to the start of the line."],
    ["$", "Move to the end of the line."],
    ["dd", "Delete the current line."],
    ["dw", "Delete from cursor through the word."],
    ["ciw", "Change inside the current word."],
  ],
  levels: [
    {
      id: 1,
      title: "Left Slash",
      concept: "h movement",
      mode: "typed",
      prompt: "Move one character left.",
      answer: "h",
      acceptedAnswers: ["h"],
      hint: "Home-row left.",
      explanation: "h moves the cursor left in normal mode.",
    },
    {
      id: 2,
      title: "Down Strike",
      concept: "j movement",
      mode: "typed",
      prompt: "Move one line down.",
      answer: "j",
      acceptedAnswers: ["j"],
      hint: "The down key is one of Vim's home-row motions.",
      explanation: "j moves the cursor down.",
    },
    {
      id: 3,
      title: "Up Cut",
      concept: "k movement",
      mode: "typed",
      prompt: "Move one line up.",
      answer: "k",
      acceptedAnswers: ["k"],
      hint: "The up motion sits between j and l.",
      explanation: "k moves the cursor up.",
    },
    {
      id: 4,
      title: "Right Dash",
      concept: "l movement",
      mode: "typed",
      prompt: "Move one character right.",
      answer: "l",
      acceptedAnswers: ["l"],
      hint: "Home-row right.",
      explanation: "l moves the cursor right.",
    },
    {
      id: 5,
      title: "Next Word",
      concept: "w motion",
      mode: "typed",
      prompt: "Jump to the start of the next word.",
      answer: "w",
      acceptedAnswers: ["w"],
      hint: "Think word.",
      explanation: "w moves forward to the next word.",
    },
    {
      id: 6,
      title: "Back Word",
      concept: "b motion",
      mode: "typed",
      prompt: "Jump back to the previous word.",
      answer: "b",
      acceptedAnswers: ["b"],
      hint: "Think back.",
      explanation: "b moves backward by word.",
    },
    {
      id: 7,
      title: "Line Edges",
      concept: "0 and $",
      mode: "typed",
      prompt: "Move to the end of the current line.",
      answer: "$",
      acceptedAnswers: ["$"],
      hint: "Use the symbol also used for line end in many patterns.",
      explanation: "$ moves to the end of the current line.",
    },
    {
      id: 8,
      title: "Delete Line",
      concept: "dd operator",
      mode: "typed",
      prompt: "Delete the current line.",
      answer: "dd",
      acceptedAnswers: ["dd"],
      hint: "Repeat the delete operator for the whole line.",
      explanation: "dd deletes the current line.",
    },
  ],
};
